[package]
name = "scout"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "scout"
path = "src/main.rs"

[dependencies]
cardstack-lib = { path = "../cardstack-lib" }
clap.workspace = true
anyhow.workspace = true
walkdir.workspace = true
serde_json.workspace = true
crossterm = "0.27"
ratatui = "0.26"
