[package]
name = "stencil"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "stencil"
path = "src/main.rs"

[dependencies]
cardstack-lib = { path = "../cardstack-lib" }
clap.workspace = true
anyhow.workspace = true
serde_json.workspace = true
serde.workspace = true
walkdir.workspace = true
chrono.workspace = true

